# Generated by Django 2.1.7 on 2019-03-05 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('date_travel', models.DateTimeField(auto_now=True)),
                ('time_travel', models.CharField(max_length=6)),
                ('amount', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
                ('number_seats', models.CharField(max_length=3)),
                ('ride_detail', models.TextField(max_length=200)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
